#!/usr/bin/env bash

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
NAME="$( basename $0 )"

export PIPENV_PIPFILE="${ROOT_DIRECTORY}/Pipfile"
pipenv run python3 "${ROOT_DIRECTORY}/${NAME}.py" "$@"
